title:            "TedYin's Blog"
description:      "Java Programer"
url:              "http://tedyin.me"
signoff:          "TedYin"
disqus_shortname: tedyin
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         Blog
    url:          /
  - name:         Feed
    url:          /feed.xml
  - name:         About
    url:          /about
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
