title:            TedYin
url:              http://tedyin.me
permalink:        pretty
pygments:         true
markdown:         rdiscount
rdiscount:
extensions:     [smart]
google_analytics: ""
timezone:         China
paginate: 5
links: 
  - name:         About
    url:          /about