title:            		"TedYIn"
description:		"TedYin ‘ s record !"
url:              		"http://tedyin.me"
signoff:			"TedYIn"
permalink:        /:title.html
pygments:         true
google_analytics: UA-21332781-7

paginate: 5
links: 

- name:		About
   url:          	/about

markdown:        redcarpet
redcarpet:
extensions:     [smart]