title:            TedYin
url:              http://tedyin.me
description: "TedYin 's Record !"
permalink:        pretty
pygments:         true
markdown:         rdiscount
rdiscount:
extensions:     [smart]
google_analytics: ""
timezone:         China
paginate: 6
links: 
  - name:         About
    url:          /about
